### PR TITLE
remove whitespace in curl options resulting in CURLE_WRITE_ERROR (23)

### PR DESCRIPTION
**Pull request by reviczky**
This patch fixes probably a typo in data-crl.lua and data-sch.lua for the curl option using "insecure".

### CODE REVIEW

**Comment by mojca** [comment]
This is not upstream repository. Please send the patch to Hans.

**Comment by hmenke** [comment]
@mojca http://nopullrequests.com/  Issues, Wiki, and Projects can be disabled in the repo settings.

**Comment by adityam** [comment]
@hmenke Actually, if we are adding a bot, it may be better to post a message to dev-context mailing list rather than close the issue. In this case, the patch should be forwarded to Hans. (I'll do that now)

**Comment by adityam** [comment]
This has been fixed upstream in 35a569ef13b42755e7469cf93d3e4982e12252d6

**Pull request closed without merging**
